baseURL = 'https://nav.pyxly.sbs/'
languageCode = 'en-us'
title = '普联星驿-文章'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"